In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.sample(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
528,2019-03-11 12:25:53,2019-03-11 12:30:36,1,0.89,5.5,0.00,0.00,6.30,yellow,credit card,Flushing,East Flushing,Queens,Queens
4054,2019-03-06 18:59:37,2019-03-06 19:08:13,1,1.49,8.0,2.21,0.00,14.51,yellow,credit card,Upper East Side South,Yorkville East,Manhattan,Manhattan
5836,2019-03-08 09:00:09,2019-03-08 09:05:29,1,0.90,5.5,1.85,0.00,8.15,green,credit card,Woodside,Jackson Heights,Queens,Queens
3358,2019-03-30 02:22:16,2019-03-30 02:36:27,3,3.50,13.0,3.35,0.00,20.15,yellow,credit card,Meatpacking/West Village West,Midtown Center,Manhattan,Manhattan
1075,2019-03-17 10:52:03,2019-03-17 11:44:35,1,9.15,39.0,8.46,0.00,50.76,yellow,credit card,Financial District South,Central Park,Manhattan,Manhattan
1094,2019-03-10 00:20:46,2019-03-10 00:25:46,1,0.70,5.0,2.20,0.00,11.00,yellow,credit card,East Village,East Village,Manhattan,Manhattan
5155,2019-03-31 12:23:52,2019-03-31 13:01:26,1,16.86,52.0,12.21,5.76,73.27,yellow,credit card,Garment District,JFK Airport,Manhattan,Queens
1797,2019-03-22 19:39:58,2019-03-22 19:57:21,1,1.91,12.0,3.26,0.00,19.56,yellow,credit card,Midtown East,Clinton West,Manhattan,Manhattan
3060,2019-03-05 19:32:50,2019-03-05 20:03:36,1,5.62,24.0,8.49,0.00,36.79,yellow,credit card,Times Sq/Theatre District,Seaport,Manhattan,Manhattan
5122,2019-03-01 17:05:48,2019-03-01 17:13:13,1,1.10,7.0,2.25,0.00,13.55,yellow,credit card,Times Sq/Theatre District,Clinton East,Manhattan,Manhattan

In [ ]:
df.sample(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
2449,2019-03-22 06:37:30,2019-03-22 06:57:24,1,4.49,17.0,2.03,0.0,24.28,yellow,credit card,Battery Park City,Midtown Center,Manhattan,Manhattan
568,2019-03-11 16:55:42,2019-03-11 17:12:36,1,1.90,11.5,3.15,0.0,18.95,yellow,credit card,TriBeCa/Civic Center,Gramercy,Manhattan,Manhattan
2960,2019-03-07 02:05:11,2019-03-07 02:20:48,1,5.21,17.0,6.24,0.0,27.04,yellow,credit card,Midtown South,Old Astoria,Manhattan,Queens
5343,2019-03-02 09:13:39,2019-03-02 09:19:13,1,0.77,5.5,1.76,0.0,10.56,yellow,credit card,Greenwich Village North,Union Sq,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan

In [ ]:
df.head(15)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
11,2019-03-20 19:39:42,2019-03-20 19:45:36,1,1.53,6.5,2.16,0.0,12.96,yellow,credit card,Upper West Side South,Manhattan Valley,Manhattan,Manhattan
12,2019-03-18 21:27:14,2019-03-18 21:34:16,1,1.05,6.5,1.00,0.0,11.30,yellow,credit card,Murray Hill,Midtown Center,Manhattan,Manhattan
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.00,0.0,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.00,0.0,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan

In [ ]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [ ]:
df['color']

0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object

In [ ]:
df['color'].isnull().sum()

0

In [ ]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
(df.isnull().sum()/6433)*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

In [ ]:
## delete a column
df.drop('pickup_zone',axis=1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.drop('pickup_zone',axis=1,inplace=True)

KeyError: "['pickup_zone'] not found in axis"

In [ ]:
df.drop(['pickup','color','payment','total'],axis=1)

,dropoff,passengers,distance,fare,tip,tolls,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,West Village,Manhattan,Manhattan
3,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.drop(['pickup','color','payment','total'],axis=1,inplace=True)

In [ ]:
df.drop([2,3,6430,6432],axis=0)

,dropoff,passengers,distance,fare,tip,tolls,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...
6426,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,East Concourse/Concourse Village,Queens,Bronx
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East Flatbush/Remsen Village,Brooklyn,Brooklyn